# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Fallstudien zur Datenanalyse - ifes@FOM"
theme = "hugrid-master"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # Meta
    title = "Fallstudiensammlung zur Datenanalyse"
    subtitle = "Es könnten 42 sein."
    author = "ifes"
    description = "Hier steht eine Beschreibung"
    keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Fallstudie lesen"

    # Footer text
    footertext = "Made by [ifes@FOM](https://www.fom.de/forschung/institute/ifes.html), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
